# Generated by Django 6.0.1 on 2026-03-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
