# Generated by Django 6.0.1 on 2026-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_stock_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
